version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
    restart: always

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: always

